### ISSUE TITLE
Any way to make ASAN work on macOS?

### ISSUE THREAD

**Issue by Kixunil** [japaric/rust-san#3]
According to https://clang.llvm.org/docs/AddressSanitizer.html ASAN works on macOS and I've successfully tried it with C. It doesn't work with Rust though. Is there any way to make it work? What'd need to be done to port it?

**Comment by japaric** [comment]
Someone already did the work (rust-lang/rust#41352) but I don't know if the usage is the same. I have no macOS to test it.

**Comment by Kixunil** [comment]
Thank you! I guess I forgot to update the compiler. I'll look at it tomorrow (I have macOS only at work) and I'll let you know.

**Comment by Kixunil** [comment]
It works, thank you!
